services:
  db:
    image: pgvector/pgvector:pg16
    container_name: da_agent_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-da_agent_db}
    ports:
      - "5432:5432"
    volumes:
      - da_postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: da_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio_da
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - da_minio_data:/data
  

volumes:
  da_postgres_data:
  da_minio_data: